baseURL = 'https://ljy501.github.io/'
locale = 'zh-CN'
title = "Liu Junyu's Blog"
theme = 'PaperMod'
enableRobotsTXT = true

[params]
  env = 'production'
  author = 'Liu Junyu'
  description = '刘峻宇个人博客测试'
  ShowReadingTime = true
  ShowWordCount = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  comments = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about/'
    weight = 2
  [[menu.main]]
    identifier = 'blog'
    name = 'Blog'
    url = '/blog/'
    weight = 3
  [[menu.main]]
    identifier = 'contact'
    name = 'Contact'
    url = '/contact/'
    weight = 4
